name: Continuous Integration
on:
  push:
    branches:
      - "2.5-stable"
  pull_request:
    branches:
      - "2.5-stable"
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }} (Ruby ${{ matrix.ruby }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
        ruby: ["2.7", "3.3"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: "Set Up Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: script/cibuild
